### ISSUE TITLE
Upgrade from ipfsapi to ipfshttpclient

### ISSUE THREAD

**Issue by rbval** [hCaptcha/hmt-escrow#112]
ipfsapi gets deprecated 31 Dec 2019, ipfshttpclient is the new version of that

**Comment by posix4e** [comment]
looks done to me

**Comment by rbval** [comment]
How? We still have ipfsapi in requirements https://github.com/hCaptcha/hmt-escrow/blob/master/Pipfile

**Comment by posix4e** [comment]
Oh saw it in the pipfile.lock

**Comment by rbval** [comment]
Actually you were right, we had updated to `ipfshttpclient`, `ipfsapi` was just a wrapper.
