### ISSUE TITLE
Smart contract performance and security enhancement

### ISSUE THREAD

**Issue by rbval** [hCaptcha/hmt-escrow#119]
## Goal
Perform an external security audit on the `Escrow.sol` contract and try to optimize its gas costs.
## Context
The project is at a stage where it runs fluently in the Rinkeby network, where publishers are getting paid through the `Escrow.sol` contract. However, we would like to get a better sense of the current security and performance posture of the project.

## Scope
- Perform an external security audit on the `Escrow.sol` contract.
- Provably optimize gas costs of the `Escrow.sol` contract by refactoring existing code.

### Bonus points
- Add solidity level tests
- Enhance existing javascript tests

## Deliverables
- A security audit report of the vulnerabilities in `Escrow.sol` emailed to @rbval (don't add to this public repo).
- A benchmark document that shows the improvement in gas costs.
- A PR with gas optimization code changes (and tests for bonus points).

## Overall requirements
- Treat this as you would a real-world project that would be used and modified by others in the future (ie documentation, tests, etc)
- Ask as many questions as you want to ensure that we're on the same page in terms of what is required
- Spend as much time as you want to do this, there's no limit or minimum; but please be sure to communicate honestly how long it took
- Create a PR to this repo when ready with your result, which we'll use to ask questions and review with you

If you have any questions please let us know! Good luck!

**Comment by posix4e** [comment]
This bounty could possibly be a medium depending on how much work is done.

**Comment by KadenZipfel** [comment]
I'd be willing to take this on.

**Comment by posix4e** [comment]
Let's see what you got.

**Comment by KadenZipfel** [comment]
Gas Optimizations: https://github.com/hCaptcha/hmt-escrow/pull/131
Security audit being emailed to @rbval
