### ISSUE TITLE
Break apart unit tests and doc tests

### ISSUE THREAD

**Issue by posix4e** [hCaptcha/hmt-escrow#128]
Currently, we believe that our doc tests have not fully supplanted the unittests, in terms of readability. We still want our doctests for our whole API, but perhaps they could be made shorter and supplanted with small unittests, and slightly smaller doctests. Use your best judgement and show us some beautiful tests. It probably makes sense to do a PR per module that you update, and you will get a small or medium bounty credit depending on the size of the PRs.

**Comment by uivlis** [comment]
Hi @posix4e can I take on this one? This will take 2-3 days, hopefully far less than my previous bounty 😄 
No, the T-shirt has not arrived yet... Didn't you get some tracking code for the package?

**Comment by posix4e** [comment]
Yes!

**Comment by posix4e** [comment]
> Hi @posix4e can I take on this one? This will take 2-3 days, hopefully far less than my previous bounty 
> No, the T-shirt has not arrived yet... Didn't you get some tracking code for the package?

They said a few weeks. Checkin in 2

**Comment by uivlis** [comment]
Alright, I started work today, and made a fresh clone of the project, however, I'm having all sorts of fails when running the tests, most of this kind:
```
An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist.
```
Is that ok, should I just move forward?

**Comment by posix4e** [comment]
It's expecting a background running minio I believe so your bucket commands
will work

**Comment by uivlis** [comment]
Hmm, not sure if I understand... I was running a minio in the background, yet the fails persist.

**Comment by posix4e** [comment]
1. Maybe start to see what bucket it is trying to connect to
2. Does that directory exist in minio? I'm guessing  just minio wasn't
setup right

if you want we can hack together on a call just grab a slot on
calendly.com/alexnewman2

**Comment by uivlis** [comment]
Just booked a slot.
