### ISSUE TITLE
DOS on escrow.sol contract for reputationOracle and recordingOracle fees 

### ISSUE THREAD

**Issue by Aleione** [hCaptcha/hmt-escrow#140]
Contract: Escrow.sol, EscrowFactory.sol

DESCRIPTION

This vulnerability prevents reputationOracle and recordingOracle from withdraw fees. Since the function finalizePayouts is public, anyone can call this function with input an array containing a big value in order to prevent Orcales from transfer fees to their address when they call bulkPayOut.

ATTACK SCENARIO
Suppose an Escrow instance was created and the setup function was submitted by canceler in order to set reputationOracle, recordingOracle and other parametres, so the status variable is pending.

Given A attacker, R1 and R2 reputation and recording oracles, M amount chosen in order that M less oracle Fees is bigger than HMtoken totally supply.

1)	A attacker submit a finalizePayouts tx with input parameter an array containing only uint256 M, in line 256 the value M less fees is added  to the storage array finalAmounts 

2)	When R1 calls bulkPayOut, in line 229 transferBulk of hmtoken contracts reverts if 
bulkPayOut input _recipients and finalamounts have different lengths. So in order to have same lengths, _amounts input array must have length equal to _recipients – 1.
In this case, to transfer fee to oracles (line 231-232) the statement at line 229 must be true. But the first amount of the bulk will not be transferred since the value M is too big, so transferBulk returns a value smaller than _recipients.length and in this way statement always false, so no fee transfers.

3)  The only way to reset finalamount is in line 230 in the transferBulk scope that will never be called. So this is a perpetual dos

PROPOSED IMPACT
This attack can prevent Oracles to gain fees, so the incentivation system proposed does not work since oracles are not rewarded for their services.

FIX 
I suggest to change privacy modifier of finalizePayouts from public to internal in order  the function can be called only by bulkPayOut that can be used only by reputationOracle. In this way nobody can attack the fees system

line 253 of Escrow.sol:
from:
function finalizePayouts(uint256[] _amounts) public returns (uint256, uint256) {
to:
function finalizePayouts(uint256[] _amounts) internal returns (uint256, uint256) {

Alessandro Bergamaschi

**Comment by posix4e** [comment]
Can you provide the fix in a pr format? And sign the cla?

**Comment by Aleione** [comment]
ok, i modify it.

Il giorno sab 8 feb 2020 alle ore 20:44 Alex Newman <
notifications@github.com> ha scritto:

**Comment by rbval** [comment]
@Aleione added this to the project board. Could you open a PR? Check https://github.com/hCaptcha/hmt-escrow/blob/master/CONTRIBUTING.md for contributing guidelines.

**Comment by rbval** [comment]
Here's the CLA to sign:  https://app.hellosign.com/s/IGBgHJ4y

**Comment by Aleione** [comment]
PR sumbitted and CLA signed
