### ISSUE TITLE
Add a collection of "trusted handlers" that can perform actions behalf of the original contract deployer.  Support canceling of jobs

### ISSUE THREAD

**Issue by gaieges** [hCaptcha/hmt-escrow#149]
Thinking something like providing a list of possible gas_payers with pub/priv keys so that we can eliminate problems that may occur when deploying multiple jobs at once.

Q: do we do this with requester keys as well?

cc: @rbval @posix4e

**Comment by rbval** [comment]
The most elegant solution should be the following:
1. Add a dictionary of "trusted handlers" in the contract that can be looked up in O(1) time.
2. When the requester launches a new escrow contract, it can decide which its "trusted handlers" are.
3. This way all our services can have separate wallet addresses and can perform storing and bulk payouts without colliding with each other.

**Comment by gaieges** [comment]
Does that address this issue? The problem we were trying to solve with this was that two wallets in use at the same time (ie two separate job deploys) collide with each other
