### ISSUE TITLE
Make raffling less noisy

### ISSUE THREAD

**Issue by rbval** [hCaptcha/hmt-escrow#186]
We give an error log for every failed raffle. Only give an error if all raffling attempts fail, not just one.

**Comment by gaieges** [comment]
Try to capture the log messages in these tickets too too so we know what we're fixing

**Comment by posix4e** [comment]
Alas it still seems a bit noisey. It would be nice if it only sent the error when it actually fails after retry. Warn would be the appropiate level but i'm stilll seeing raffling errors

**Comment by rbval** [comment]
@posix4e this is addressing those raffling errors you see.
