### ISSUE TITLE
Reduce Escrow gas usage

### ISSUE THREAD

**Issue by posix4e** [hCaptcha/hmt-escrow#197]
Currently we are using too much gas. With our move from IPFS to s3, we shouldn't update the contract nearly as much.

TODO
- [x] Remove intermediate results hash and url
- [x] Only update the URL on start, and potentially on finish
- [x] Only update the hash when the contract is complete

Now store intermediate results should only use gas on the first call. This should greatly reduce gas use

**Comment by posix4e** [comment]
I've got to test this on our system

**Comment by uivlis** [comment]
@posix4e After 2 months, the only thing left is this: https://github.com/hCaptcha/hmt-escrow/issues/214. Once that's finished, I can't wait for the bounty prize! (450$ if I remember correctly since there were 2 issues: [this one](https://github.com/hCaptcha/hmt-escrow/issues/197) being medium/large (300$) and [another one](https://github.com/hCaptcha/hmt-escrow/issues/201) being small/medium (150$)).

**Comment by posix4e** [comment]
Do we have any estimates on before and after gas usage?

**Comment by uivlis** [comment]
No, not yet, I'll make a script for that (to query the blockchain). What sort of gas metrics would you be most interested in? Like average lifetime (from deploying to completing) cost across all Escrows contracts, before and after? Or just the intermediate-store-results part (which is the one I've affected most with this change)?

**Comment by posix4e** [comment]
Either or both is fine with me

**Comment by uivlis** [comment]
Moving this to https://github.com/hCaptcha/hmt-escrow/issues/235.

**Comment by uivlis** [comment]
@posix4e Estimates are in:
```
----------- Results -----------

Average change in gas: -28.748%
-------------------------------

Change breakdown by functions
-------------------------------
pending: -6.375%
-------------------------------
launch: -26.116%
-------------------------------
intermediate: -50.608%
-------------------------------
unkown: -8.297%
```

Let me know if this is an acceptable delta for the bounty prizes.
