### ISSUE TITLE
Bonded Reputation Agent (Decentralized)

### ISSUE THREAD

**Issue by posix4e** [hCaptcha/hmt-escrow#203]
Currently, Exchange operators usee a variety of techniques to prevent abusive content from getting on the captcha chain. For example, hCaptcha, an Exchange on the HUMAN network, has numerous automatic systems which  prevent bad content from being loaded into the system, as well as real-time reporting and remediation. 

Currently whitelists are used to manage this, but as more Exchanges come online and job requests become more decentralized, we need a distributed social mechanism to prevent abusive content from being requested. The HUMAN whitepaper refers to a Reputation Agent which inspects the content of tasks to be performed, assuring nothing inappropriate gets on the chain. 

We want you to design and implement the bonding system for the Reputation Agent, using the flow described in the whitepaper.

It should have the following properties:

- [ ] A user can put up a bond to become a reputation agent
- [ ] Any user can vouch for the safety of the job with that bond.
- [ ] If the receiving Exchange nominated in the smart contract detects abuse, it will trigger an abort-for-abuse call, which will automatically allow the remaining reputation agents to vote on whether a reputation agent did his job right.
- [ ] If he didn't, the bond will be released by the Reputation Oracle to all contributors exposed to that job, proportional to their exposure. 
- [ ] The reputation agent will thus be required to re-bond before they can authorize new jobs

**Comment by uivlis** [comment]
@posix4e @evin What's up with this?

**Comment by gaieges** [comment]
Taking this out of the sprint for now, need some more input

**Comment by uivlis** [comment]
Taking this off for the moment.
