### ISSUE TITLE
Benchmark gas utilization

### ISSUE THREAD

**Issue by gaieges** [hCaptcha/hmt-escrow#214]
As part of deploying new hmt-escrow we want to benchmark the cost of gas before and after the change, and see it empirically

**Comment by gaieges** [comment]
We can likely do this by looking at the wallets that we have and rollout the new changes to token and escrow and then graph / look at the wallet values over time with a annotation on when we made the token/escrow changes to see the delta.

Moving to 50

**Comment by gaieges** [comment]
To HMT 51

**Comment by gaieges** [comment]
to Hmt 52

**Comment by gaieges** [comment]
Moving to 53

**Comment by gaieges** [comment]
Lets convert this into a bounty, can you write up a new ticket with enough details for someone to pick this up @uivlis ?

**Comment by uivlis** [comment]
😿 But... but... I wanted the bounty for myself! I'll conform though if that's what you decided, but just in case you weren't aware of this: https://github.com/hCaptcha/hmt-escrow/issues/197#issuecomment-703526906.

**Comment by gaieges** [comment]
We were just trying to get more capacity, this is one that we can have someone external run through and have you focus on the more interesting internal stuff.

**Comment by uivlis** [comment]
Got it, launching the bounty.

**Comment by uivlis** [comment]
https://github.com/hCaptcha/hmt-escrow/issues/235
