### ISSUE TITLE
Deploy new hmt token

### ISSUE THREAD

**Issue by uivlis** [hCaptcha/hmt-escrow#222]
Deploy again the hmtoken+escrow contracts, since they have been recently changed in order to save gas.

Possibly wait for testing the whole integrated hCaptcha suit before deploying.

**Comment by gaieges** [comment]
@uivlis will try to close this out today / tomorrow

**Comment by uivlis** [comment]
New HMToken: 0x4C18A2E51edC5043e9c4B6b0757990A4Ac13797f
