### ISSUE TITLE
Adjust the contracts as per CertiK's audit report.

### ISSUE THREAD

**Issue by uivlis** [hCaptcha/hmt-escrow#223]
Use the report to make the necessary changes in order to improve the gas usage and code quality of the contracts. No security issues were found, but we should clean up their minor items.

**Comment by gaieges** [comment]
Closing out as we did most of the changes already

**Comment by uivlis** [comment]
Hmm, no, I did not? Not sure why this was closed, reopening this.

**Comment by uivlis** [comment]
Hopefully solved in https://github.com/hCaptcha/hmt-escrow/pull/225.

**Comment by gaieges** [comment]
Don't need to move this, already done in the PR above
