### ISSUE TITLE
Create a new launchsite with a blockchain-themed dashboard (and other features...)

### ISSUE THREAD

**Issue by uivlis** [hCaptcha/hmt-escrow#228]
hCaptcha needs a new website, let your imagination run dry!

Features required:

- [ ] blockchain-related data pleasently presented in the dashboard.
- [ ] others... @posix4e @gaieges?

**Comment by gaieges** [comment]
What sort of stuff are you looking to get an understanding of on this dashboard? Can you enumerate what that would look like?

**Comment by e271828-** [comment]
This needs more details before being posted. Closing until product work is fleshed out properly.
