### ISSUE TITLE
Parametrize the `get_w3` function to choose between `https` or `wss` connection to provider

### ISSUE THREAD

**Issue by uivlis** [hCaptcha/hmt-escrow#236]
Recently, I stumbled on a situation where I could only use the `wws` connection to Infura, because events-related RPC methods were only available via Websockets, so I had to build my own web3 object and could not rely on the generic `get_w3` function (which can only use `https`).

This issue requires to parametrize the `get_w3` function (possibly like this: `get_w3("wss") | get_w3("https")`) so that we could have both the `https` and `wss` provider out of the box.

**Comment by sahzhang** [comment]
I can take this issue, started work here https://github.com/sahzhang/hmt-escrow/tree/feat/sahzhang_236_add_wss_flag

**Comment by sahzhang** [comment]
I can take this issue. I started the work here https://github.com/sahzhang/hmt-escrow/tree/feat/sahzhang_236_autodetect_wss_provider. I went with a different approach to use a helper function in `web3.py`'s native `AutoProvider` implementation. That way when `HMT_ETH_SERVER` is set with any endpoint, `get_w3` should set up the provider with the supported provider. 

For context: here is the `AutoProvider` helper function https://github.com/ethereum/web3.py/blob/master/web3/providers/auto.py#L46

**Comment by gaieges** [comment]
@sahzhang unfortunately this ticket hasn't been made a bounty yet (see [guidelines here](https://github.com/hCaptcha/hmt-escrow#found-a-bug-or-a-feature-request)).  We appreciate the work but at the moment we will need to wait on merging and completion of this ticket.

**Comment by sahzhang** [comment]
> @sahzhang unfortunately this ticket hasn't been made a bounty yet (see [guidelines here](https://github.com/hCaptcha/hmt-escrow#found-a-bug-or-a-feature-request)). We appreciate the work but at the moment we will need to wait on merging and completion of this ticket.

np happy to help regardless of bounty, just saw that it was a quick fix and wanted to put up a PR
