### ISSUE TITLE
Add Event emits for missing status changes in the Escrow contract. 

### ISSUE THREAD

**Issue by excerebrose** [hCaptcha/hmt-escrow#243]
Discovered this during building out a tool to check gas utilisation of contracts:
In `Escrow.sol`, no events are emitted for following state changes: `aborted`, `cancelled`,   `completed `, and `paid `.

Recommendation is to add then asap as they help with much granular level tracking & debugging.

**Comment by e271828-** [comment]
I believe this was done to reduce gas costs. We could certainly have a debug version that does this, but need to evaluate the tradeoffs.

**Comment by excerebrose** [comment]
According to the ethereum documentation, the cost of gas is calculated as follows:
```
gas_units = 375 +  unindexedBytes * 8 + indexedTopics * 375
```
So, 
for an event of the following spec:
```
event Event(address escrow_addr);
```
the gas cost is going to be:
```
units = 375 + 20*8
units = 375 + 160
units = 535 
```

Average gas price (on mainner) is about 15 GWEI, which equates to `535*15 = 8,025 GWEI`, a normal transfer transaction is always upwards of 21,000 GWEI, this is nothing compared to that.

Also, as we discussed most of the Escrow logic will be happening on the discussed chain, hence this cost will be further reduced.

It will also have the added benefit of helping with the wrapppers we have been discussing about building.

**Comment by uivlis** [comment]
Where are we on this @excerebrose @e271828- ?

**Comment by excerebrose** [comment]
This was kind of left out, didn't get an approval.
