### ISSUE TITLE
Clean and upgrade smart contracts to 0.5.5+ versions

### ISSUE THREAD

**Issue by rbval** [hCaptcha/hmt-escrow#69]

**Comment by gaieges** [comment]
Can you elaborate @rbval ? Do you mean 0.4.4?

**Comment by rbval** [comment]
Talking about Solidity's compiler and smart contract versions. 0.5.5 is the current newest one, our smart contracts are in 0.4.24 version. @gaieges

**Comment by gaieges** [comment]
Relevant when we start the audit process.  Additional features, security fixes. Requires us to make code changes to the .sol files.

Likely need to get away from the python solidity stuff, and use node or go instead (separate task)

**Comment by rbval** [comment]
We decided to go with a wrapper library that supports 0.4.24 for python for now. An implementation with local abis together with s3 might be something we do next.
