### ISSUE TITLE
Create a separate abis folder in order to get the most updated version of solidity contracts whenever needed

### ISSUE THREAD

**Issue by rbval** [hCaptcha/hmt-escrow#73]
# Description
Currently we have our solidity contracts in 0.4.24 version. The latest version is in 0.5.5 and has introduced few great improvements as explicitly describing array-based variables (array, list, mappings) to have a memory prefix.

Currently we compile our contracts with `py-solc` every time we build the Dockerfile which can be a bit extranous work. Also, `py-solc` only supports up to 0.4.25 version so we are left with relying on the project updating its compiler to the latest one.

An alternative approach would be to have a separate `abis` folder where we would directly store our pre-compiled solidity contract abis. 

The benefits:
1. Save time on building the project
2. Have access to the latest contract versions

Disadvantages:
1. Every time we do changes to our solidity contracts we have to manually compile and update their corresponding abis to the project folder structure.

While its cool to have automatic compiling of contracts, updating solidity contracts will always have a slower cycle than traditional software development. Sometimes new changes need to go through a new audit, etc. Compiling the contracts manually shouldn't have any downside from that point of view. 

## Tasks
- Implement a python compilation script that uses `solc` instead of `py-solc` that compiles all files in `contracts/` and outputs them to the `abis` folder
- Migrate over the compilation of contracts from old implementation to the new implementation in `hmt_escrow/eth_bridge.py` (https://github.com/hCaptcha/hmt-escrow/blob/master/hmt_escrow/eth_bridge.py#L22)

**Comment by e271828-** [comment]
Seems reasonable. I don't think we want to rely on py-solc long term, since it does seem to be lagging quite a bit.

**Comment by gaieges** [comment]
Are there any alternatives to py-solc/solc that is worth exploring?

I liken the `abi` folder to a `build` folder in like a js project - you can commit it if you want or not, but at least in the repo there's a built version.  Is that accurate?  Could be useful from the perspective of a consumer of hmt-escrow where they dont want to muck with any of the build stuff and users dont need all of the additional solc stuff to use hmt-escrow.

**Comment by uivlis** [comment]
Hi guys, can I take on this one? As an estimate, I think it will take 2-3 days.

**Comment by rbval** [comment]
Hi @uivlis and thanks for showing interest! After doing some recent research I came across `eth-brownie` and `py-solc-x` that are showing some interest development in python based web3 libraries. 

I consider it would be worth a shot taking a look at those if this issue of >0.5 versions could be solved by using either one of those libraries in favor of doing an `abis/` folder.

If you're interested in that, we can move this issue to the other issue found at https://github.com/hCaptcha/hmt-escrow/issues/142.

Let me know what you think.

**Comment by uivlis** [comment]
Sure, that seems like a good idea.

**Comment by rbval** [comment]
Ok, going to close this issue in favor of that and move the bounty there. Welcome aboard!

Linking to #142 .

**Comment by uivlis** [comment]
Closing since #195 should've closed this.
