### ISSUE TITLE
Append  results

### ISSUE THREAD

**Issue by posix4e** [hCaptcha/hmt-escrow#79]
We should have some way of automatically appending to the  results.

```
1. Generate a ipns links (intermediate and final) on startup of the contract both results When you launch the contract  https://github.com/hCaptcha/hmt-escrow/blob/master/hmt_escrow/job.py#L348
2. Update  results ipfs and add new ipns to new ipfs at https://github.com/hCaptcha/hmt-escrow/blob/master/hmt_escrow/job.py#L469
3. Update results with new ipfs and update ipns
https://github.com/hCaptcha/hmt-escrow/blob/master/hmt_escrow/job.py#L637
4. https://github.com/hCaptcha/hmt-escrow/blob/master/hmt_escrow/job.py#L652
Have complete download newest ipfs results, and add hash.
```

**Comment by posix4e** [comment]
- So it turns out you can use ipns to just automatically update the pointer in the contract. This means we only need to update the intermediate results ipns endpoint.
- We don't need to update the hash until we are done with contract completely.

**Comment by nickgeoca** [comment]
The proposed design is to give each Escrow a unique IPNS link. This can be done by generating an IPFS keypair for each IPNS link. The end result of an Escrow's IPNS link will be: an IPFS with all Escrow results/manifest/etc data in it.

**changes to the smart contract**
1) Put the IPNS link onchain during Escrow construction.
2) Add an option to update the hashes (when needed) in the `storeResults` and `bulkPayOut` code. For example, `bulkPayOut` can be called without writing the final results URL & hash.

**changes to the python** (1 & 2 are the same as above)
 1) Create an IPNS link then pass it to Escrow on construction. 
 2) Optional write results/manifest/etc data onchain.
 3) Our python `upload` function puts results/manifest/etc data on IPFS. The changes to `upload` are this: a) `upload` will concatenate the results/manifest/etc data to the data of all previous uploads for a given escrow; b) load this new data file to IPFS; c) set the IPNS url to point to the new IPFS data file.

**Comment by nickgeoca** [comment]
Maybe putting cart before the horse, but here are some open questions:
1) What is a good way to serialize/deserialize the results/manifest/etc data, given it is a series of concatenations? Something along the lines of? ... `<manifest-data-1><delimiter><manifest-data-2><delimiter>` . What is a good binary delimiter?
2) Each IPFS keypair is secretly isolated to a PEM file via the very convenient python IPFS API. It would be a good idea to back this up or else IPNS links can't be updated. The question is do we need access to these keys? As long as the PEM file is there, we will be able to publish IPNS updates. Each keypair is keyed by the escrow address.
3) Do we want to call `storeResults` if we don't intend to write out the hash & url to storage? If it is called, even though the purpose would not to be store it onchain, it would be written to the Ethereum logs. Here is the code below to show what I mean. `emit IntermediateStorage(_url, _hash);`
```
    function storeResults(string _url, string _hash) public {
        require(expiration > block.timestamp, "Contract expired");  // solhint-disable-line not-rely-on-time
        require(msg.sender == recordingOracle, "Address calling not the recording oracle");
        require(
            status == EscrowStatuses.Pending ||
            status == EscrowStatuses.Partial,
            "Escrow not in Pending or Partial status state"
        );

        intermediateResultsUrl = _url;
        intermediateResultsHash = _hash;

        emit IntermediateStorage(_url, _hash);
    }
```

**Comment by e271828-** [comment]
Just to clarify, this is one IPNS link per Escrow (i.e. smart bounty), per *agent*, i.e. one for recO and one for repO?

**Comment by nickgeoca** [comment]
Yeah one per recO and repO makes sense. Otherwise a single party would have to be trusted with updating the IPNS link for both the recO and the repO.

**Comment by nickgeoca** [comment]
For the question I mentioned above
3) Do we want to call `storeResults` if we don't intend to write out the hash & url to storage?
The blockchain call looks like it would cost around 2k in gas.

**Comment by posix4e** [comment]
Ask that in a different way

**Comment by gaieges** [comment]
Done in https://github.com/hCaptcha/hmt-escrow/pull/122
