### ISSUE TITLE
DISCUSSION: Move timeout decorator to storage

### ISSUE THREAD

**Issue by rbval** [hCaptcha/hmt-escrow#83]
We use the timeout decorator in bcs to fix urllib3 connection problems, what if we moved it to hmt-escrow's storage layer?

https://pypi.org/project/timeout-decorator/

**Comment by posix4e** [comment]
sgtm
-- 
+14045076749 Alex

**Comment by gaieges** [comment]
Yeah the timeout thing is useful, what problem are you trying to solve though? the ipfs call?

**Comment by gaieges** [comment]
More of an action item here than a discussion I think.
