### ISSUE TITLE
Separate ipfs connection to its own function

### ISSUE THREAD

**Issue by rbval** [hCaptcha/hmt-escrow#84]
We experience the urllib3 connect reuse every time we instantiate a new Job which results in an error:
```
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): ipfs:5001
DEBUG:urllib3.connectionpool:http://ipfs:5001 "GET /api/v0/cat?stream-channels=true&arg= HTTP/1.1" 500 None
```
we could fix this by letting the client using hmt-escrow store a variable of the ipfs client that they would use to pass to the `download` and `upload` instead.

**Comment by gaieges** [comment]
It's kind of surprising to me that the *reuse* is the problem here .. looking at that request it seems the ipfs is throwing a 500, can you capture the output of that to get a little more color on what the 500 error is?
