### ISSUE TITLE
Add support for public key lookup

### ISSUE THREAD

**Issue by rbval** [hCaptcha/hmt-escrow#86]
We are already seeing copy paste in many of our services as `get_pk_from_address`. Let's move that to be used from the hmt-escrow itself.

Definition of Done:
1. Add `get_pk_from_address` to `eth_bridge`
2. Setup `eth-kvstore` to the local blockchain infra like we do `hmt-token`: https://github.com/hCaptcha/hmt-escrow/blob/master/docker-compose.yml#L37
3. Add doctests for setting a new pk, and fetching that pk with the same address that stored it.

**Comment by gaieges** [comment]
Try to hammer out today
